# Generated by Django 5.1.5 on 2025-01-21 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Management', '0003_quizset_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('marks', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Admin_Management.quizset')),
            ],
        ),
    ]
