# Generated by Django 5.1.5 on 2025-01-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submitted_answers',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
